language: r
pandoc_version: 2.9.2.1
sudo: required
apt_packages:
  - r-cran-rjava
before_install:
  - sudo $(which R) CMD javareconf
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
    - secure: "vMFp/GRMKWpv9YniHGYWxxwqBDvEsKgytFxFZ3y6YHyfSVd3vWy0EK9zq34X6Zlsp6F6/J9aFapes+MI0wd5H6WYWGso3dDF4x2FCsFnLium4pmR65e6RlbSIhUvolMiWdkq5Xr5CC/8kfA8/lw2MvDAJw65aAYP3o+1DnelsrRSOz6Jb/7Dc+HdS6kyFXO8x44S2KT6IKDf2T9754dqbK+GBZzPhxfkHsFd0jlZGBGFjMTJM0e+up+lpavmIufsP3gwmgYi22PE6tR8o7e0wSXE+W4RavU56R2Ee1BBe+S9W7+fSvnHqb7j1pgr0OVqeFnl/So1OzQCdFy+3w8XL9jQF4mA5mpYKR+iNVqIquwXI+mU1svgHff82aw9frdXbqW+Y699zVsQnmRPT3GSszB72Gdk+nNxGfMhd+vPJQS0WYkjAJMFjNI2E+MdeC5GaN1Iv9A+ogmQdgqvxqjIerEEpvnvsbf8+EfgSjVVGxOjyWV5ilSK8uNjIQn69UY+2h6djlxgI7O5i8muzZ3uzpN2yUhUhTADL2V7SNYGpOZSLHasv4flmL0RhcuYfoBDjVAla8C4i1+NmJdTrSwx/BXvD9RA/GRKgxFeEEgNSrCdLvZEGX7G0ouYjeMZyQ5X+lI2oOcV0C8AvEQnRE2Pbl05GwAzVAK5MYCecednV14="
before_script:
- chmod +x ./deployment/_build.sh
- chmod +x ./deployment/_deploy.sh
script:
- travis_wait 45 "./deployment/_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deployment/_deploy.sh
